version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies

  build:
    commands:
      - echo Build started
      - echo Build completed successfully

  post_build:
    commands:
      - echo Sending Slack notification
      - |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"🚀 CI/CD SUCCESS! Website deployed automatically via AWS."}' \
        $SLACK_WEBHOOK

artifacts:
  files:
    - '**/*'